from cgitb import enable
from tokenize import Name
import discord
from discord.ext import commands
import simple_search_engine
import auctionator_graph_generator

intents = discord.Intents.default()
intents.message_content = True
intents.messages = True

def read_token():
    with open("token.txt","r") as f:
        lines = f.readlines()
        return lines[0].strip()
token = read_token()

bot = commands.Bot(intents=intents, command_prefix=commands.when_mentioned_or("$ac "))

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")

@bot.command(name="price")
async def price(ctx,*,msg_1):
    global found_itemss
    found_itemss = simple_search_engine.sse_search_start(msg_1)
    response_msg = ""
    if len(found_itemss) <= 0:
        response_msg += " No matches found for "+msg_1+"!"
    elif len(found_itemss)==1:
        response_msg += "1."+found_itemss[0]
    else:
        for i,line in enumerate(found_itemss,1):
            response_msg += str(i)+". "+line+"\n"
    embedVar = discord.Embed(title="Please type in: $ac choose <number> ", color=0x00ff00)
    embedVar.add_field(name="Choose from list:",value=response_msg)
    choose.reset_cooldown(ctx)
    await ctx.send(embed=embedVar)



@bot.command(name="choose")
@commands.cooldown(1, 99999999999999999999, commands.BucketType.user)
async def choose(ctx,msg):
    try:
        output_item_name = simple_search_engine.sse_pick_item(msg,found_itemss)
        print(output_item_name)
        _,_, latest_price, latest_price_date, _, trend_coef = auctionator_graph_generator.calculation_before_plotting(output_item_name)

        latest_price = latest_price*10000
        gold = int(latest_price/10000)
        silver = int((latest_price-(gold*10000))/100)
        bronze = int(latest_price-(gold*10000)-(silver*100))
        latest_price_prettyfied = str(gold)+" :yellow_circle: "+str(silver)+" :white_circle: "+str(bronze)+" :brown_circle: "
        if trend_coef > 0:
            trend_string = "Rising"
        elif trend_coef == 0:
            trend_string = "Stable"
        elif trend_coef < 0:
            trend_string = "Decreasing"

        if output_item_name.find("ERR")!=-1:
            await ctx.send(output_item_name)
        else:
            graph_image = discord.File("graph.png")
            embedVar2 = discord.Embed(title="Current pricing information", color=0x00ff00)
            embedVar2.set_image(url="attachment://graph.png")
            embedVar2.set_footer(text="Info generated by Auction Crane")
            embedVar2.add_field(name="Item name",value=output_item_name,inline=False)
            embedVar2.add_field(name="Latest Price",value=latest_price_prettyfied,inline=True)
            embedVar2.add_field(name="Latest Price date",value=latest_price_date,inline=True)
            embedVar2.add_field(name="Price trend",value=trend_string,inline=True)
            choose.update(enable=False)
            await ctx.send(embed=embedVar2,file=graph_image)
    except NameError:
        await ctx.send("Please use $ac price <item name> first!")

@bot.event
async def on_command_error(ctx, error):
	if isinstance(error, commands.CommandOnCooldown):
		await ctx.send("You can't choose twice!\nUse $ac price <item name> first!")

bot.run(token)